<a href="https://colab.research.google.com/github/Diluc99/python/blob/main/Exp13_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

arr = [1, 2, 3, 4, 5]
series = pd.Series(arr)
print(series)


0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
import pandas as pd

arr = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(arr, index=index)
print(series)


a    1
b    2
c    3
d    4
e    5
dtype: int64


In [ ]:
import pandas as pd

lst = [10, 20, 30, 40, 50]
series = pd.Series(lst)
print(series)


0    10
1    20
2    30
3    40
4    50
dtype: int64


In [ ]:
import pandas as pd

data = {'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}
series = pd.Series(data)
print(series)


a    10
b    20
c    30
d    40
e    50
dtype: int64


In [ ]:
import numpy as np

# np.array()
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# np.arange()
arr = np.arange(10)
print(arr)

# np.zeros()
arr = np.zeros(5)
print(arr)

# np.ones()
arr = np.ones(5)
print(arr)

# np.random.rand()
arr = np.random.rand(5)
print(arr)

# np.max()
max_val = np.max(arr)
print(max_val)

# np.min()
min_val = np.min(arr)
print(min_val)


[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0.82530232 0.79984371 0.00698863 0.3049354  0.54900157]
0.825302319995285
0.006988629168414584


In [ ]:
import pandas as pd

data = [1, 2, 3, 4, 5]
series = pd.Series(data)

# sum()
print(series.sum())

# mean()
print(series.mean())

# median()
print(series.median())

# std()
print(series.std())

# var()
print(series.var())

# min(), max()
print(series.min(), series.max())

# iloc[]
print(series.iloc[1:3])

# loc[]
series_with_index = pd.Series(data, index=['a', 'b', 'c', 'd', 'e'])
print(series_with_index.loc['b':'d'])

# str.contains (for string series)
str_series = pd.Series(['apple', 'banana', 'cherry', 'date'])
print(str_series.str.contains('a'))


15
3.0
3.0
1.5811388300841898
2.5
1 5
1    2
2    3
dtype: int64
b    2
c    3
d    4
dtype: int64
0     True
1     True
2    False
3     True
dtype: bool
